### ISSUE TITLE
How to Install Repo

### ISSUE THREAD

**Issue by thecodechef** [Guilouz/repository.guilouz#1]
hey im currently using 1.2.1 of the estaury mod but i want up to date versions so how can install your repo

**Comment by Guilouz** [comment]
See http://forum.kodi.tv/showthread.php?tid=267343

**Comment by thecodechef** [comment]
hi thanks for responding but u see the problem is that is what i did the first time it didnt work i had to extract it then compress just the skin itself and do it that way then it worked , also can u fix the studio tags in movies/tv  shows they are constantly flickering and showing the actual icons thank you
