### ISSUE TITLE
Player Menus

### ISSUE THREAD

**Issue by MarioGreen** [Guilouz/repository.guilouz#101]
Using Skin Estuary MOD for KODI 17 Krypton and while playing a video (movie, tv show, etc) there are the icons for settings, subtitles and bookmarks. Well, the menu pops up with a distance from the icon which makes it hard to use the mouse to catch the menu items before it disappears as the mouse passes in the gap between the popup and the icon.
I think either make the menu appear on clicking as in the regular Estuary skin or get the menu closer to stick to the icons area.

**Comment by Guilouz** [comment]
Development for Kodi 17 is stopping.
