### ISSUE TITLE
estuarymodv2 kodi 18 / Focus lost when fixed views enabled

### ISSUE THREAD

**Issue by hawkeyexp** [Guilouz/repository.guilouz#113]
I noticed that focus is lost on home screen when moving to widgets oder categories when fixed views is enabled in skin settings. It makes no diff of normal menu or reduced size is eanbled.

**Comment by Guilouz** [comment]
Be more explicit. Which fixed view ?
It's strange because fixed view have nothing to see with widgets.

**Comment by hawkeyexp** [comment]
sorry it is called forced views in your skin - here are my settings for fixed view which replicates the behaviour on two systems. By the way: it is also changing views for example in addons - is it possible you make it also setable for addons or to exclude it ?

![screenshot002](https://user-images.githubusercontent.com/761728/29335311-854075fe-820a-11e7-8f99-cae7a95b2e8e.png)

**Comment by Guilouz** [comment]
Just try to set same forced views as you and I have no issue with focused widgets on home. There is no link between forced views and home widgets.
Not possible to force views for other parts of skin.

**Comment by hawkeyexp** [comment]
I have checked it again: removed my kodi folder to reinit with clean system. Installed repo and your skin - after it all addon deps in skin settings - than installed a backup of my master system config and the bug is present :-) I added the backup file to ckeck it out :-)
[Estuary.modv2 Skinbackup (2017-08-15 23.36.05).zip](https://github.com/Guilouz/repository.guilouz/files/1226531/Estuary.modv2.Skinbackup.2017-08-15.23.36.05.zip)

**Comment by hawkeyexp** [comment]
Problem identified and solved: i didn't install repository.marcelveldt repo cause it was not possible (not included in official repo or your repo) and after manualsearch and install some updates arrived and the bug is gone.
To prevent errors like this it make sense you add his repo to yours to include an install way :-)

**Comment by Guilouz** [comment]
If you had read the first page of the forum, you would have seen it ;)
