### ISSUE TITLE
estuarymodv2 kodi 18 / Widget view

### ISSUE THREAD

**Issue by hawkeyexp** [Guilouz/repository.guilouz#114]
It would be great if you can fit widget layout on home to 5x2 or 6x2 when categorie is visible.
Currently the best view is in settings widget. Possble you can change spacing between items like in the favourites widget to make 5x2 or 6x2 fully visible in screen when reduzed menu is aktivated. Also the alignment and spacing in weather widget is different to all other.

**Comment by Guilouz** [comment]
No because Estuary have layout adaptable depending of resolution. For request please use forum and no report issue here.
