### ISSUE TITLE
estuarymodv2 kodi 18 / Bottom right media info symbols

### ISSUE THREAD

**Issue by hawkeyexp** [Guilouz/repository.guilouz#117]
Would be nice if you can add a background to media info row on bottom to make it more readable. Possible a dark shadow in background etc. like for the categories items.

![screenshot000](https://user-images.githubusercontent.com/761728/29330093-60b8cd1a-81f8-11e7-9227-466c0ef2c8d0.jpg)

**Comment by Guilouz** [comment]
There is already a background for mediaflags and you can also change opacity of top and bottom bar in skin settings.
