### ISSUE TITLE
smartlist rules issue

### ISSUE THREAD

**Issue by piotrasd** [Guilouz/repository.guilouz#13]
today i tested smart playlist, normal is possible add few rules to one smartplaylist 
here we dont have that possibility (like be missing buttons)
after i add one .. i cannot add more.

![screenshot025](https://cloud.githubusercontent.com/assets/773012/16717777/23f5c5a8-4712-11e6-83de-5bd55fefb252.png)

like here
![600px-musicxsp4](https://cloud.githubusercontent.com/assets/773012/16717697/3ef9f528-4711-11e6-8d6c-c448b71ae792.png)
source:
http://kodi.wiki/view/Smart_playlists#

PS. i will here raport bugs/issue if no problem (i dont want spam forum)

Update:
After added buton to main menu and connect with my created smart playlist (cartoons for kids)
skin before add button ask me about action (play or show ) i choose show ...

But after recreate main manu i get button but no action when i try ... 
when back to skin settings and change that to Play ... then working playing smart playlist
(only showing dont work )

**Comment by Guilouz** [comment]
I think it's not skin issue. I have already see that in a report thread.

For showing, I just try and it's working for me.

**Comment by piotrasd** [comment]
ok i will try reinstall skin, because for me is to many issue, maybe after x time upgrade somthing missmatch
