### ISSUE TITLE
[skin.estuary.modv2] Fanart (View 502) of Episodes Always Displays Season 01 Poster

### ISSUE THREAD

**Issue by mgonzales71** [Guilouz/repository.guilouz#152]
Probably should display the "general" poster artwork instead since the smaller inset of the current season poster of the selected episode is displayed.

notice s16e14 shows season 1 poster to the left:

![kodi_2018-04-05_01-29-39](https://user-images.githubusercontent.com/6510026/38355405-aba96750-3871-11e8-924d-f6e95373ecc7.png)

Thanks,

Mario

**Comment by Guilouz** [comment]
I don't understand your issue...

**Comment by mgonzales71** [comment]
Look at the photo I attached.

I have highlighted **Episode 14 of Season 16** in the list.

The artwork (poster) says "Season One" - it should probably just be poster.jpg
not season01-poster.jpg

So as an example:

## Instead of showing:

![season01-poster](https://user-images.githubusercontent.com/6510026/38402660-9554c4b2-3912-11e8-9562-e2dca0055220.jpg)

## should probably show:

![poster](https://user-images.githubusercontent.com/6510026/38402665-a031803c-3912-11e8-9ba2-1f8d7def1a2e.jpg)

I hope I explained a little better.

I just noticed that Season 1 poster was always being displayed no matter what Season the highlighted episodes were.

**Comment by Guilouz** [comment]
Working fine for me, fanart view show seasons posters

![screenshot010](https://user-images.githubusercontent.com/12702322/38517742-34af37a6-3c3b-11e8-803d-3268b122be88.png)

![screenshot011](https://user-images.githubusercontent.com/12702322/38517752-3dce9e58-3c3b-11e8-867e-20f1313cf5b5.png)

Make sure you have downloaded all artworks.

**Comment by s0ulslack** [comment]
Can confirm this in Fanart view and also List view, the first season poster is displayed for all seasons.

**Comment by Guilouz** [comment]
Check your posters seasons Artworks in Artwork Beef addon

![screenshot000](https://user-images.githubusercontent.com/12702322/38524134-e06cd7a8-3c4d-11e8-9c65-fbbd0be58f4d.png)

**Comment by mgonzales71** [comment]
I have all artwork downloaded - actually artwork bred by default doesn’t download artwork but stores the image URL’s.

I can assure you that the post for SEASON 1 is ALWAYS displayed as the (what I would expect to be shows is the root level (NON SEASONAL poster for the highlighted show) in FANART view for TV SHOW EPISODES since you are displaying the current season as a smaller poster already in that view.


Do this:

Find a TV show that you have with multiple seasons and go the any season other then season 1 - so for instance: season 2 episode 1

In fanart view you will see to the left while that episode is selected the poster for season 1.

See this image to hopefully understand what I am trying to explain 

![example](https://i.imgur.com/2EG25lP_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by mgonzales71** [comment]
Sorry for typos it’s late and I’m sleepy 💤🙃

**Comment by mgonzales71** [comment]
Oh and I that you show different behavior but the issue I am seeing is for all my tvshows - I will provide better info tomorrow - I need to get to bed hehehe 

Night for now (or morning) lol

**Comment by Guilouz** [comment]
Just try this : Find a TV show that you have with multiple seasons and go the any season other then season 1 - so for instance: season 2 episode 1

All is working fine for me each seasons and each episodes have their own season poster respectively.

Try to delete your image cache and see.

**Comment by mgonzales71** [comment]
Ok I will try that next.

but just so you can see this is the artwork I have downloaded so you can see I do in fact have the right files, etc

![2018-04-12_11-46-59](https://user-images.githubusercontent.com/6510026/38697672-7f502c12-3e47-11e8-854c-75fda39449f5.png)

**Comment by mgonzales71** [comment]
That is so WEIRD!  
but it fixed it.. sorry about the false alert!

![kodi_2018-04-12_11-53-50](https://user-images.githubusercontent.com/6510026/38697993-6566600e-3e48-11e8-8022-9f71104423cd.png)

But I am curious - why do you use a smaller version of the same poster artwork in this view?

Anyway I will close this issue and thank you for your help and great work on this skin mod.

I may open a pull request with some things I have added that you may wish to add in the future once I am happy with tinkering with them myself.

Mario

**Comment by mgonzales71** [comment]
FYI - What all I did to resolve this was:
1) remove source and content from library
2) this started a clean video library function (normal thing to happen)
3) quit Kodi
4) deleted Textures DB and Thumbnail folder
5) added source back and let the scan repopulate the video library and image cache

**Comment by Guilouz** [comment]
Just try this and all my posters are good... Maybe an issue with external artworks. I use artworks stored in my database.

**Comment by mgonzales71** [comment]
Ok - I have my artwork on local disk in a folder downloaded and then scanned into the Kodi Library..

userdata\Database\MyVideos109.db
that then are cached in 
userdata\Database\Textures13.db and the userdata\Thumbnails\ directory  

Is that what you mean?  If I have the view set to All Videos it works as expected, but when set to unwatched and it is hiding all but the most recent episode of a tv show in a non season 1 season the poster from season 1 will always be shown.

you are not seeing this behavior on your system?

I am going to do a test install of Kodi and scan just 1 tv show in with multiple seasons and only the addons that get installed to support the skin and see if I still see this issue.

Hopefully if you watched the video screen recording you can see I am not going crazy 
LOL

Thanks,

Mario

**Comment by mgonzales71** [comment]
This may help solve the issue. 
I used webinterface.developer and found the following $INFO labels and their values while I was viewing Episode 02 of Season 03 of The Expanse.

Note the change in Watched vs Unwatched - that has to be the source of the FanArt view issue.

## Unwatched: 

Container.Art(season.poster)		**_\TVShows\The Expanse (2015)\season01-poster.jpg_**
Container.Art(thumb)				**_\TVShows\The Expanse (2015)\season01-poster.jpg_**

Container.Art(tvshow.poster)		\TVShows\The Expanse (2015)\poster.jpg
Container.ListItem.Art(season.poster)	\TVShows\The Expanse (2015)\season03-poster.jpg
Container.ListItem.Art(tvshow.poster)	\TVShows\The Expanse (2015)\poster.jpg
ListItem.Art(season.poster)			\TVShows\The Expanse (2015)\season03-poster.jpg
ListItem.Art(tvshow.poster)			\TVShows\The Expanse (2015)\poster.jpg

## All:

Container.Art(season.poster)		\TVShows\The Expanse (2015)\season03-poster.jpg
Container.Art(thumb)				\TVShows\The Expanse (2015)\season03-poster.jpg

Container.Art(tvshow.poster)		\TVShows\The Expanse (2015)\poster.jpg
Container.ListItem.Art(season.poster)	\TVShows\The Expanse (2015)\season03-poster.jpg
Container.ListItem.Art(tvshow.poster)	\TVShows\The Expanse (2015)\poster.jpg
ListItem.Art(season.poster)			\TVShows\The Expanse (2015)\season03-poster.jpg
ListItem.Art(tvshow.poster)			\TVShows\The Expanse (2015)\poster.jpg


## Looking at the images used in **View_502_FanArt.xml**:

**$VAR[FanartImageVar]**
```

	<variable name="FanartImageVar">
		<value condition="ListItem.IsParentFolder">special://skin/extras/home-images/movies.jpg</value>
		<value condition="Skin.HasSetting(hide_thumbforspoiler) + Integer.IsLess(ListItem.Playcount,1) + Container.Content(episodes)">$VAR[MediaFanartVar]</value>
		<value condition="Container.Content(episodes) + !String.IsEmpty(ListItem.Thumb)">$INFO[ListItem.Thumb]</value>
		<value condition="Skin.HasSetting(EnableExtraFanart)">$VAR[MediaFanartVar]</value>
		<value>$INFO[ListItem.Art(fanart)]</value>
	</variable>


```
**$VAR[IconWallPosterVar]**

```
	<variable name="IconWallPosterVar">
		<value condition="!String.IsEmpty(ListItem.Art(animatedposter)) + Skin.HasSetting(Skin_EnableAnimatedPosters)">$INFO[ListItem.Art(animatedposter)]</value>
		<value condition="!String.IsEmpty(ListItem.Art(season.poster)) + Container.Content(episodes)">$INFO[ListItem.Art(season.poster)]</value>
		<value>$INFO[Listitem.Art(poster)]</value>
	</variable>


```
**$INFO[ListItem.Art(poster)]**
Used in Line 153 & Line 165

At the TV Show Level
\TVShows\The Expanse (2015)\poster.jpg

At the TV Season(s) Level
			01		\TVShows\The Expanse (2015)\season01-poster.jpg
			02		\TVShows\The Expanse (2015)\season02-poster.jpg
			03		\TVShows\The Expanse (2015)\season03-poster.jpg

At the TV Episode Level
Empty (Not Set)

Did not seem to change with view being Watched / Unwatched


I am not sure if this is a bug or what but maybe the skin uses a fallback image or cache or something. 

But I think for **Episode** Views you should use **Container.ListItem.Art(season.poster)** or **ListItem.Art(season.poster)** since they seem to be set properly regardless of Watched / Unwatched

**Comment by mgonzales71** [comment]
Also I have not yet tested if this makes a difference but using the following may yield better results since you already utilize the script:

https://github.com/marcelveldt/script.skin.helper.service/wiki/Listitem-Properties---Artwork

**Comment by mgonzales71** [comment]
I am sure you already know of web devhelper @ https://github.com/rmrector (just in case you wanted/needed link)

Thanks again Cyril!

Mario

**Comment by Guilouz** [comment]
This variables not corresponding to the left poster.

Try to replace this variable in Variables.xml line 3772 and said me if it's fix this issue :

> <variable name="PosterVar">
		<value condition="ListItem.IsParentFolder + ![Control.IsVisible(55) + Container.Content(files)]">DefaultFolderBackPoster.png</value>
		<value condition="Container.Content(actors) | Container.Content(directors)">$INFO[Container.ListItem.Art(thumb)]</value>
		<value condition="!String.IsEmpty(Listitem.Art(season.poster)) + Container.Content(seasons)">$INFO[Listitem.Art(season.poster)]</value>
		<value condition="!String.IsEmpty(Listitem.Art(tvshow.poster)) + Container.Content(seasons)">$INFO[Listitem.Art(tvshow.poster)]</value>
		<value condition="!String.IsEmpty(Container.Art(tvshow.poster)) + Container.Content(seasons) + Window.IsActive(movieinformation)">$INFO[Container.Art(tvshow.poster)]</value>
		<value condition="!String.IsEmpty(Container.Art(season.poster)) + Container.Content(episodes)">$INFO[Container.Art(season.poster)]</value>
		<value condition="!String.IsEmpty(Container.Art(tvshow.poster)) + Container.Content(episodes)">$INFO[Container.Art(tvshow.poster)]</value>
		<value condition="!String.IsEmpty(ListItem.Art(tvshow.poster)) + !String.IsEqual(listitem.dbtype,season)">$INFO[ListItem.Art(tvshow.poster)]</value>
		<value condition="!String.IsEmpty(ListItem.Art(animatedposter)) + Skin.HasSetting(Skin_EnableAnimatedPosters)">$INFO[ListItem.Art(animatedposter)]</value>
		<value>$INFO[ListItem.Art(poster)]</value>
	</variable>

>

**Comment by mgonzales71** [comment]
I am closing this as it doesn't seem to be isolated to your skin.

I tested views in a few other skins that used tv show posters and I see the same behavior so this has to be a bug in Kodi with episode containers with unwatched view option set.  maybe it's like the "all" list item which doesn't get populated or something?  who's knows :)

I am switching episodes view to "wide list" to save my sanity !

thanks

**Comment by s0ulslack** [comment]
Nice detective work Mario. Please file a bug with kodi
