### ISSUE TITLE
[Enhancement] Live TV - currently running

### ISSUE THREAD

**Issue by M2k80** [Guilouz/repository.guilouz#157]
hello,
it would be very nice if you could add in one of these red scares whats just running on a channel like on my screenshot,

and maybe if there is enough space, whats running next
Thank you!

![2018-04-27 19_40_07-kodi1](https://user-images.githubusercontent.com/6137556/39376882-813cc716-4a53-11e8-899b-2d0a74ef4d2e.png)

**Comment by Guilouz** [comment]
There is already two kinds of widgets, see

![screenshot000](https://user-images.githubusercontent.com/12702322/39382900-7ce9fcb0-4a67-11e8-9ea2-210ce4f94f4d.png)

![screenshot001](https://user-images.githubusercontent.com/12702322/39382903-81c8bff0-4a67-11e8-87e3-303056863338.png)

**Comment by M2k80** [comment]
oh ok, what i have to change that it looks like on your second pic?

**Comment by Guilouz** [comment]
In Skin Settings / Home Menu / Show media names with widgets names setting.

**Comment by M2k80** [comment]
thank you very much...
