### ISSUE TITLE
DialogBusy + DialogVideoInfo bg diffuse

### ISSUE THREAD

**Issue by mgonzales71** [Guilouz/repository.guilouz#161]
noticed that dialog busy had a diffused bg that was either out of alignment or improperly sized 

changed to white for emphasis: 

![kodi_2018-05-22_17-24-04](https://user-images.githubusercontent.com/6510026/40397052-613ae33a-5de5-11e8-993f-8591ed7d7a19.png)

took a crack at updating xml for ya:

[DialogBusy.xml.txt](https://github.com/Guilouz/repository.guilouz/files/2029042/DialogBusy.xml.txt)

result (diffuse color set back to black btw):

![kodi_2018-05-22_17-22-29](https://user-images.githubusercontent.com/6510026/40397116-b48fe602-5de5-11e8-9573-93f3d954952d.png)

**Comment by mgonzales71** [comment]
This is modv2 skin btw.

**Comment by Guilouz** [comment]
It's not an issue, reduced dialogbusy is enable when 'Watch trailer in fullscreen' setting is disable and my window is correctly placed, see

![screenshot006](https://user-images.githubusercontent.com/12702322/40417837-08ad7d26-5e81-11e8-9018-595213fe5c8b.png)

![screenshot008](https://user-images.githubusercontent.com/12702322/40417863-13b405b4-5e81-11e8-9555-aa6c6b9696df.png)

**Comment by mgonzales71** [comment]
ok but notice the busy dialog spinner and overlay you took a screenshot of is different then what I am seeing.

that is strange.

also I wasn't watching a trailer.

IDK - maybe add a Player.HasMedia or Player.HasVideo and !LiveTV or Audio? 

I won't stress out over it .... it just caught my attention and I was bored 😃

**Comment by Guilouz** [comment]
What resolution do you use ?

**Comment by mgonzales71** [comment]
laptop has native resolution of 1280 x 800 - yea different aspect ratios make simple things a bit more tricky with skins.

I guess that is why my first impulse was to go full screen and center busy diffuse and spinner.

guess you have the aspect ratio control with align and aligny and percentages for x/y and how etc 

I thought the new adaptive skin layout fixed this with the various addon.xml <res> entries adjusting for the various scaring factors... maybe I misunderstood that.

Anyway - yup it's the differing aspect ratio / scaring thats to blame.

I was super early / late hehe

Take care!

Mario
