### ISSUE TITLE
texture watermarking? on couple of icons

### ISSUE THREAD

**Issue by mgonzales71** [Guilouz/repository.guilouz#163]
defaultaddonssearch.png and defaultmusicsearch.png seem to have an alpha watermark or some kind of artifact.

you can kind of make it out:

![screenshot000](https://user-images.githubusercontent.com/6510026/41813568-3a57e166-76ed-11e8-884e-3fbb0df5df95.png)

this is an exaggerated version of the actual image:

![current_defaultaddonssearch](https://user-images.githubusercontent.com/6510026/41813575-532293c6-76ed-11e8-9789-5d3690306555.png)

quickly made couple of new images in case you liked and wanted to use them. 

they are white on transparent so you can't really see them but they are there :)

------defaultaddonssearch------
![defaultaddonssearch](https://user-images.githubusercontent.com/6510026/41813584-7d91d900-76ed-11e8-8f85-c532dd84de73.png)
------defaultmusicsearch------
![defaultmusicsearch](https://user-images.githubusercontent.com/6510026/41813585-7db84afe-76ed-11e8-9343-4008cc458611.png)
----------------------------------

negative versions of images
![defaultaddonssearch - copy](https://user-images.githubusercontent.com/6510026/41813598-c61e7fb6-76ed-11e8-8fc8-276ceb927058.png)
![defaultmusicsearch - copy](https://user-images.githubusercontent.com/6510026/41813599-c63b9a88-76ed-11e8-9228-88b2fd6caf3e.png)

example of one of the images in use in skin:

![screenshot003](https://user-images.githubusercontent.com/6510026/41813623-5ed89a66-76ee-11e8-90f7-09a1527fae29.png)

anyway obviously not a big deal - just happen to notice it and wanted to send a quick FYI

Take care!

Mario

**Comment by Guilouz** [comment]
Thanks, it's fixed.
