### ISSUE TITLE
[skin.estuary.mod2] NextAired TVGuide: Yesterday (& +13/+14/+16 days) always Blank/Empty

### ISSUE THREAD

**Issue by mgonzales71** [Guilouz/repository.guilouz#165]
**UPDATE**: +13/+14/+16 days also (possible 15th or others depending if data should be present)  Obviously unless you have shows airing on specific days it is difficult to test.  But temporarily renaming the custom XML to disable to check against what the skin shows with the custom XML's in place has been verified for yesterday and +13/+14/+16 days.

Thanks!

Been trying to sort thru the skin to find out why "Yesterday" is always blank/empty showing "no broadcasts" when in fact there were.

I use the 15 day with "yesterday" config for the script.

If I remove the skin customized script-NextAired-TVGuide2.xml the addon script shows items for yesterday but don't display properly (pretty sure it defaults to confluence support)

here is the script run in the skin without and then with the custom xml files in place.

![screenshot000](https://user-images.githubusercontent.com/6510026/44856492-6b11e300-ac22-11e8-9d17-28f4720c8c62.png)
![screenshot001](https://user-images.githubusercontent.com/6510026/44856493-6b11e300-ac22-11e8-9aad-ac0426f8955b.png)

At first I thought it may be a PARAM issue or a <visible> conditional but I am obviously missing something

anyway lowest priority - I will keep looking for it and hopefully it will pop out at me.

I noticed some <xvisible> conditions in the xml files - is that new for Kodi skins and I missed it?  or maybe something used by the script?  typo?  there are 32 and 14 of them respectively used.

Thanks again

Mario

**Comment by Guilouz** [comment]
It's strange, I have checked my condition visibility and it's look good like in original file. I need to wait to have items in 'yesterday' to try some things.

**Comment by mgonzales71** [comment]
It could be something other than a visibility condition - it's been tougher than most for me to unravel... I will keep looking as well.   Thanks for looking into it when you have time.. like I said lowest of priorities for me.

**Comment by mgonzales71** [comment]
also - to add more oddness to things I went and checked results using another skin (embuary) and noticed it's not just "yesterday" that is not showing info what should be showing:

![screenshot000](https://user-images.githubusercontent.com/6510026/44966554-c1b44100-aef0-11e8-9cb5-b612e78e7aea.png)

notice the days missing data:

![honey_screenshot001](https://user-images.githubusercontent.com/6510026/44966575-d1cc2080-aef0-11e8-94c7-c62b1dcd3a09.png)
![honey_screenshot002](https://user-images.githubusercontent.com/6510026/44966576-d1cc2080-aef0-11e8-88d3-ab45fa40dcff.png)
![honey_screenshot003](https://user-images.githubusercontent.com/6510026/44966577-d1cc2080-aef0-11e8-942c-91fb4a66d91c.png)

**Comment by mgonzales71** [comment]
also for sanity checked modv2 skin without custom xml to see if data shows for 13th 14th and 16th:

![screenshot001](https://user-images.githubusercontent.com/6510026/44966672-620a6580-aef1-11e8-9ecc-33a0741f6987.png)

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
