### ISSUE TITLE
View_54_InfoWall.xml unbalanced ()'s on coditionals in visible 

### ISSUE THREAD

**Issue by mgonzales71** [Guilouz/repository.guilouz#166]
Line 1224 the 4 conditions are unbalanced )'s (missing outer most

corrected:

`				<visible>[String.IsEmpty(ListItem.Art(poster)) + String.IsEmpty(ListItem.Art(tvshow.poster)) + String.IsEmpty(ListItem.Art(season.poster)) + String.IsEmpty(ListItem.Art(animatedposter))]</visible>`

also update with a couple other things that - tired but can't sleep but I think these are the corrected line

### Insomnia again 

should line 235 be like this?

				`<texture fallback="DefaultDirector.png" background="true">http://localhost:52307/getthumb&amp;title=$ESCINFO[ListItem.Label,, imdb]</texture>`

and 1320 like this:
`
				<visible>![String.IsEmpty(ListItem.Art(poster)) + String.IsEmpty(ListItem.Art(tvshow.poster)) + String.IsEmpty(ListItem.Art(season.poster)) + String.IsEmpty(ListItem.Art(animatedposter))]</visible>`

**Comment by mgonzales71** [comment]
ok - thought that was the issue but poster is several of the views for tv shows are now not showing the season artwork - for instance:

### poster view - tv show - seasons

![screenshot001](https://user-images.githubusercontent.com/6510026/47348881-43aa2600-d667-11e8-81cf-a9f07a5fdf64.png)

### shift view - tv show - seasons

![screenshot000](https://user-images.githubusercontent.com/6510026/47348880-43aa2600-d667-11e8-8589-6afa38008328.png)

**Comment by mgonzales71** [comment]
OK pretty sure the corrections to lines 1224 and 1320 are right since the following errors are no longer present in log file
```

01:48:49.912 T:14240   ERROR: unmatched parentheses in string.isempty(listitem.art(poster)
01:48:49.912 T:14240   ERROR: unmatched parentheses in string.isempty(listitem.art(tvshow.poster)
01:48:49.912 T:14240   ERROR: unmatched parentheses in string.isempty(listitem.art(season.poster)
01:48:49.912 T:14240   ERROR: unmatched parentheses in string.isempty(listitem.art(animatedposter)

```

**Comment by Guilouz** [comment]
Fixed, thanks.
