### ISSUE TITLE
missing buttons for radio

### ISSUE THREAD

**Issue by M2k80** [Guilouz/repository.guilouz#168]
could you please add missing buttons for radio on the OSD?

like channel guide, channel list and player info?

thank you

**Comment by Guilouz** [comment]
I don't have PVR backend so I can't work more in PVR and Radio from PVR.
If someone want to share his server it would be good.

**Comment by M2k80** [comment]
i just tried latest git, seems to be fine, buttons are now there.
for pvr you have player info....if you could that add too, would be nice. 
if not its ok too

**Comment by Guilouz** [comment]
It's added to last git.
