### ISSUE TITLE
minimalist version

### ISSUE THREAD

**Issue by Madmaxie** [Guilouz/repository.guilouz#170]
I have been a long time very happy user but MOD V2 is basically overkill for my needs (I have a separate system for music, Pictures, I do not download movies etc (internet to slow) only sports (NFL) and other functions such as YouTube, Iview, Facebook are native to my TV. As a result, I was hoping for a cut down version with a main menu with:
Movies
Movies Sets
Movie Genres
TV Shows
Favourites  (which I use for Sports and would like to rename to Sports)
Weather

The bar menu with "Favourites, File Browser, System Information/Settings, Power Options" replace the Favourites option with a Library option where you can Update, Clean, export and import.

Remove the strip menu which currently displays Genres, Sets, Update etc, (when Movies or TV Shows menu option is highlighted)

The new version "Mini MOD" should have much less code hence faster.

I basically want to be manage my large library of movies & TV Series (DVD & Blu-rays).

You would a whole segment of the market to yourself as everyone is trying to be everything for everyone and failing.

Regards

Max

**Comment by Guilouz** [comment]
I do not plan to do that and development of Estuary MOD comes to an end.
