### ISSUE TITLE
Movie Sets

### ISSUE THREAD

**Issue by Madmaxie** [Guilouz/repository.guilouz#171]
when you manage a set either to change the art or members of the set when you finish you are returned to Movie titles view not the movie set view where you started. 

I also cannot get Movie Set menu option to work the same as Movie Set in the categories menu does

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
