### ISSUE TITLE
Access to OSD settings of SkinHelper

### ISSUE THREAD

**Issue by 127-001** [Guilouz/repository.guilouz#172]
Hy. Just a small feature request :-)

Cab you give access to the following settings of SkinHelper:
- SkinHelper.ShowInfoAtPlaybackStart
- SkinHelper.AutoCloseVideoOSD
- SkinHelper.AutoCloseMusicOSD

(see https://github.com/marcelveldt/script.skin.helper.service/wiki/Settings )

**Rational for this request**: 
- The autoclose delays in kodi 18 are way too long (up to 10 seconds at playback start)
- The Info panel is huge (especially for music where there is no "SmallOSD/OSDWithoutInfo")
- I know you added a settings "Hide_OSDInfo", but it's all-or-nothing and alters the visibility of DialogSeekBar causing sometime a flash effect when seeking music. The 3 settings of SkinHelper give more control over the OSD.

Thanks.

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
