### ISSUE TITLE
[skin.estuary.modv2] Missing text in addons section

### ISSUE THREAD

**Issue by Pavuucek** [Guilouz/repository.guilouz#174]
![estuarymodv2](https://user-images.githubusercontent.com/1253845/50725030-a7d17780-10f7-11e9-83ca-fec4b50f86d9.png)
These buttons are missing their labels, no matter what language is selected.

**Comment by Guilouz** [comment]
This infolabels are from Kodi language file.

![screenshot000](https://user-images.githubusercontent.com/12702322/50739969-aa12ff00-11e7-11e9-85a5-71e4c6a62f2c.png)
