### ISSUE TITLE
Support for symbol fonts

### ISSUE THREAD

**Issue by kekukui** [Guilouz/repository.guilouz#179]
**Can symbol fonts for YouTube be added to the skin ?**

**_"This file contains a list of all fonts the skin uses."_
https://kodi.wiki/view/Fonts**

![capture](https://user-images.githubusercontent.com/20834957/52171912-5e466d80-2733-11e9-8e29-c98d8db86ea8.PNG)
![font error](https://user-images.githubusercontent.com/20834957/52171958-3a375c00-2734-11e9-8a27-81e6b4649d6a.png)

**Comment by Guilouz** [comment]
For that it's needed that arrows are in font files, it's not the case with fonts I use.

**Comment by kekukui** [comment]
I found the solution is to use a Unicode font, e.g. **Settings | Interface | Arial based**
