### ISSUE TITLE
[skin.estuary.modv2] movie with web in it's name triggers web-dl flag

### ISSUE THREAD

**Issue by C4Wiz** [Guilouz/repository.guilouz#180]
the girl in the spiders web triggers the web-dl flag to be set in the movie info

File Name: The Girl in the Spider's Web (2018).DTSHD-MA.Blu-ray.mkv

**Comment by Guilouz** [comment]
I can remove "web" word for "web-dl" flag

**Comment by C4Wiz** [comment]
> I can remove "web" word for "web-dl" flag

that worked perfectly!
