### ISSUE TITLE
[Skin.Estuary.Modv2] Feature Request

### ISSUE THREAD

**Issue by C4Wiz** [Guilouz/repository.guilouz#181]
can we also get a UltraHD bluray logo? 

like this: but black and white

![image](https://user-images.githubusercontent.com/3883521/52279056-99f55900-2926-11e9-8316-d600f925374e.png)

and add the triggers: UHD-Bluray, uhd, UHD, etc.

**Comment by Guilouz** [comment]
No need to have a difference between the bluray logo and the uhd bluray logo because with the resolution we see if it is UHD or not.
