### ISSUE TITLE
[skin.estuary.modv2] Audio and Subtitle Flags issue

### ISSUE THREAD

**Issue by C4Wiz** [Guilouz/repository.guilouz#183]
language is set to english US but audio and subtitle flags are UK flags not US flags

**Comment by Guilouz** [comment]
If you have UK flag your file is taggued with UK.
MKV file ?

**Comment by C4Wiz** [comment]
> If you have UK flag your file is taggued with UK.
> MKV file ?

Yes mkv

**Comment by C4Wiz** [comment]
i don't see any mention on UK or US in the header editor for any of my files

**Comment by C4Wiz** [comment]
ALL my discs are US releases ripped with english US audio and English US forced subs only!

**Comment by C4Wiz** [comment]
OK, i figured it out, you do not have a US flag in your skin, eng is 
![eng](https://user-images.githubusercontent.com/3883521/52904027-edec2180-31f3-11e9-83cd-2a87b30fa79c.png)

can you localize it to use a USA flag?

**Comment by HeresJonny** [comment]
There is no UK english or US english tracks when it comes to flagging audio tracks... it is simply flagged as english. Coincidentally, they speak the same language in the US and in the UK... tomato tomato

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
