### ISSUE TITLE
[skin.estuary.modv2] Navigation through custom widgets

### ISSUE THREAD

**Issue by TehTux** [Guilouz/repository.guilouz#184]
> Hi, I finally upgraded my Kodi setup today (Coreelec on S905x Box) and installed Estuary. So far I'm very impressed and want to thank all people involved for this nice skin. Unfortunately I'm facing an issue and I can't find anything on Google.
> 
> I have created a new main menu item for the YouTube add on and have added two custom widgets. When I select the item in the menu I can see the two widgets and I can navigate in the top widget. The problem is that I can navigate down to the second widget, I press down on my remote (CEC) and I hear the tone for the button press, but it never goes down to the second widget. It's working fine for the default menu item (Shows or Live TV) though.

https://forum.kodi.tv/showthread.php?tid=306757&pid=2817198#pid2817198

**Comment by TehTux** [comment]
Reproduced with Kodi 18.0 (LibreELEC 9.0.0 on Raspberry Pi 3)

**Comment by Guilouz** [comment]
It's a known issue (with Raspberry Pie only) with Skin Shortcuts addon, already reported here : https://github.com/BigNoid/script.skinshortcuts/issues/235

But there is no support since many years.

**Comment by TehTux** [comment]
Thank you for the relation. But it's not "Raspberry Pi only", see first post "Coreelec on S905x Box"
