### ISSUE TITLE
With custom menu item I cannot navigate down from first to second widget row

### ISSUE THREAD

**Issue by piejanssens** [Guilouz/repository.guilouz#187]
No problems with the standard Movie, TV, Addons etc. But when I create my own node (e.g. Concerts) and add two widgets to it (category disabled) I cannot navigate down. 
In fact it's impossible to reach the second row.

**Comment by Guilouz** [comment]
Do you use a raspberry Pi ?

It's a known issue Skin Shortcuts addon, already reported here : BigNoid/script.skinshortcuts#235

But there is no support since many years.

**Comment by piejanssens** [comment]
I have this issue on Vero4K (OSMC). 
I setup the exact same custom menu configuration on macOS where I don't have this issue.

**Comment by piejanssens** [comment]
Given that script.skinshortcuts is used by so many popular skins, don't you find it too big of a coincidence that all people in BigNoid/script.skinshortcuts#235 are EstuaryMod v2 users? 💡

**Comment by Guilouz** [comment]
Yes I know but I have no idea how to fix that because I can't reproduce this issue on OSX, Windows and LibreELEC platforms.

**Comment by piejanssens** [comment]
the_other_guy fount the possible source for this problem: https://forum.kodi.tv/showthread.php?tid=306757&pid=2854423#pid2854423

**Comment by MiloshCZ** [comment]
Hi, I have same issue at CoreElec v 9.2.0 Amlogic-ng.arm (Odroid-N2). I have tried disable "Disable the option "Share menu between compatible skins" in "Skin Shortcuts" settings" but no change.

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
