### ISSUE TITLE
Custom menu item settings overlaps with menu in background

### ISSUE THREAD

**Issue by piejanssens** [Guilouz/repository.guilouz#188]
![Schermafbeelding 2019-05-01 om 12 55 41](https://user-images.githubusercontent.com/829098/57015048-07a5de00-6c13-11e9-938b-709d1864fa77.png)

Kodi 18.2 Final

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
