### ISSUE TITLE
[skin.estuary.modv2] Movie information not showing while playing a video in the background

### ISSUE THREAD

**Issue by jake404** [Guilouz/repository.guilouz#189]
While playing a video and navigating to the movie list and clicking on a movie it will show video fullscreen. No commands are accepted except back. It seems that the movie information is hidden behind the video playback.

**Comment by jake404** [comment]
This is what it looks like:

![2019-05-04_13-40-56](https://user-images.githubusercontent.com/12189899/57178549-73d24d00-6e72-11e9-9584-b0a1496a9ba6.png)

**Comment by jake404** [comment]
After some testing, I found out that this only happens if the setting 'Play trailers in full screen' is enabled.

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
