### ISSUE TITLE
[skin.estuary.modv2] Request: Add Sample Rate in Music OSD

### ISSUE THREAD

**Issue by HeresJonny** [Guilouz/repository.guilouz#190]
In Music OSD, replace kpbs (Bitrate) with (or add) "Sample Rate" for lossless formats (FLAC, APE, PCM, MLP, DSF, etc.).

Valid options would be: 44.1kHz, 48kHz, 88.2kHz, 96kHz, 176.4kHz, 192kHz, 2.8224MHz (SACD).

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
