### ISSUE TITLE
no youtube id found

### ISSUE THREAD

**Issue by jake404** [Guilouz/repository.guilouz#192]
When trying to watch a trailer from Extended Info I get the error message 'no youtube id found'. It doesn't matter which trailer it is or which clip it is.

**Comment by HeresJonny** [comment]
And you ask here and not the developer of Extended Info... because?

**Comment by jake404** [comment]
Because I don't have this problem in other skins.

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
