### ISSUE TITLE
[skin.estuary.modv2] Center logo and show poster in OSD

### ISSUE THREAD

**Issue by jake404** [Guilouz/repository.guilouz#193]
When looking at the OSD for PVR, the logo is aligned to the bottom. Can you please center it and also show the poster if it's available? The poster is shown in the EPG.

<a href="https://ibb.co/rMfXcBY"><img src="https://i.ibb.co/y5BxYzt/2019-05-14-17-21-23.png" alt="2019-05-14-17-21-23" border="0"></a>

When looking at the OSD for movies it shows a banner instead of the poster. Can you please change so it shows the poster instead?

<a href="https://ibb.co/Yjrvw0k"><img src="https://i.ibb.co/WKTSjVy/2019-05-14-17-20-57.png" alt="2019-05-14-17-20-57" border="0"></a>

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
