### ISSUE TITLE
[skin.estuary.modv2] Posters are not visible in the 'Next Episodes' vertical widget

### ISSUE THREAD

**Issue by jake404** [Guilouz/repository.guilouz#194]
The vertical widget 'Next Episodes' with the appearance type Posters will not show any images. The empty placeholders are there and selectable.

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
