### ISSUE TITLE
non-HDR in filenames

### ISSUE THREAD

**Issue by stephen147** [Guilouz/repository.guilouz#195]
I'm having a problem with UHD logos displaying even though the media is different.

For example. the name of the file is: `Cast Away (2000) 720p HD BRRip non-HDR x265 DTS 5.1ch`

As you can see the name has `non-HDR` in it. So the problem arises from that probably.

![ image ]( https://i.imgur.com/rSW2ole.png " Image: image ")

**Comment by HeresJonny** [comment]
Talk about being stupid... you do realize that "non-HDR" has "HDR" in it and thus triggers "HDR"? Get rid of non-flags unless you want to tag it with everything that it is not.

**Comment by stephen147** [comment]
Don't worry Jonathan.

I have fixed the issue myself. Sorry for me being stupid BTW but not as ignorant as you.

I guess everyone has their faults.

**Comment by HeresJonny** [comment]
It's not an issue and deactivating the HDR-flag in the skin is not a fix. The root cause is your file naming convention. You need to re-check the skin thread over at the Kodi forums how to name your files properly.

**Comment by stephen147** [comment]
I'm fully aware of how the files should be named, thank you. This is why I posted for a fix for a feature public release.

Have you thought that perhaps having it search for `non-HDR` or `non.HDR` or `nonHDR` along with the normal `HDR` could work. After all I've easily fixed it myself.

If it supported regular expressions it would be even easier.

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
