### ISSUE TITLE
[Skin.Estuary.Mod2] Requests Home Screen

### ISSUE THREAD

**Issue by bloodykiller86** [Guilouz/repository.guilouz#196]
Hi i have a few requests and hopefully theyre possible to do

1. Add padding to right side like left. Current right side his edge of screen

2. Add a widget viewtype thats square but with labels under it

3. Between categories and widgets, can we add a up to 5x5 vertical scrolling 2nd cateogry menu where you can custom make every icon instead of using widgets. i love how you can customize categories but really dont like widgets, skin widgets is a bit slow honestly. This would make them instant load

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
