### ISSUE TITLE
skin is dead?

### ISSUE THREAD

**Issue by M2k80** [Guilouz/repository.guilouz#198]
it seems developement on this skin is dead :/ 
no more changes since 5.Feb

**Comment by DjDiabolik** [comment]
And on repo 3.0.6 it's no push ?? Because ?

**Comment by trymeouteh** [comment]
Could someone fork this to keep it alive if it is dead? It is a good skin and would like it to stay alive.

**Comment by Guilouz** [comment]
Yes development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins. That's why !
