### ISSUE TITLE
Can't add artist thumb in music library

### ISSUE THREAD

**Issue by Neelix57** [Guilouz/repository.guilouz#201]
With Estuary Mod V2, we can't add artist thumb in Kodi's music libray. It won't refresh.
After selecting the browse option in the add artwork dialog box, the name of the artist appearing in the next dialog box title is wrong. It's the name of the artist over wich the cursor been when clicking on the "artwork options" item in context menu.

[kodi.log](https://github.com/Guilouz/repository.guilouz/files/4501928/kodi.log)

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
