### ISSUE TITLE
Default Estuary Setting Out Of The Box

### ISSUE THREAD

**Issue by trymeouteh** [Guilouz/repository.guilouz#203]
I think it would be better if the Estuary MOD skin out of the box was setup looked the same as the original Estuary skin. From there users can change the settings of Estuary MOD to their liking.

This way users coming to Estuary MOD from Estuary will at first see no difference at all except for more settings to change and can tweak with the settings to change the skin. I and many like Estuary out of the box but think it is lacking features which Estuary MOD filled the void of but Estuary MOD has to be configured lots to just look the same as the original Estuary skin.

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
