### ISSUE TITLE
VPN Shortcut button

### ISSUE THREAD

**Issue by trymeouteh** [Guilouz/repository.guilouz#204]
Please add two settings in the skin which are...

- Show VPN shortcut button
- VPN shortcut button action

This button can be next to the power button or settings button and is a quick way to access your Kodi addon VPN. You can choose what the VPN addon to use by setting "VPN shortcut button action" and hide the button if you don't want it. This button will be allow quick access to your VPN addon settings weather you use OpenVPN addon or the NordVPN addon.

**Comment by Guilouz** [comment]
Development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins.
