### ISSUE TITLE
Estuary mod in KODI19 (Matrix)

### ISSUE THREAD

**Issue by romainalca** [Guilouz/repository.guilouz#205]
Hi,

Since the last update (KODI19 Matrix), it is not possible to use Estuary Mod skin.
Is an update planned for skin ?

Thanks

**Comment by Guilouz** [comment]
> Hi,
> 
> Since the last update (KODI19 Matrix), it is not possible to use Estuary Mod skin.
> Is an update planned for skin ?
> 
> Thanks

No, development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins. That's why !

**Comment by romainalca** [comment]
> > Hi,
> > Since the last update (KODI19 Matrix), it is not possible to use Estuary Mod skin.
> > Is an update planned for skin ?
> > Thanks
> 
> No, development is ended since many times because I no longer use Kodi, many developers have stopped to update their plugins and Kodi 19 have changed the way to use plugins which requires an update of all the plugins. That's why !

Oh ! Ok, sorry...
Too bad : Your skin was very useful. 
I created home menu specific for my children and i didn't find other skin with this feature.
I will see i find anything else.

Thanks a lot for your job ! ;)
