### ISSUE TITLE
PVR: channel list too big

### ISSUE THREAD

**Issue by dkadioglu** [Guilouz/repository.guilouz#79]
The list of channels is too big and overlayed by the heading in the top and the "options" string at the bottom in Kodi 18 Leia and Estuary MOD V2.
See the screenshot:
![grafik](https://cloud.githubusercontent.com/assets/1633773/25299760/bfd989fc-2702-11e7-8b1b-8874393787bb.png)
In the old version this was not the case. It would be great if you could fix that. Thanks and best.

**Comment by Guilouz** [comment]
It's not an issue. All lists in skin are working like this.

**Comment by dkadioglu** [comment]
Sorry for replying but, that's weird because in Estuary MOD 1.7.13 and all versions before that I used, this was not the case.

**Comment by dkadioglu** [comment]
Here is a screenshot:
![20170422_091126](https://cloud.githubusercontent.com/assets/1633773/25302322/1af9c606-273c-11e7-8876-2da468a127c2.jpg)

**Comment by Guilouz** [comment]
Your second screenshot is from Estuary MOD v1 for Kodi 17, first is from Estuary MOD v2 for Kodi 18.

Estuary MOD v2 is working like that for all lists with adaptive layout for every aspect ratio.

**Comment by dkadioglu** [comment]
OK, thanks for the info. That's sad because, when I'm scrolling through the channel list using the page up or page down key, I miss the channels at the top and bottom, as I can barely see them. It would be great, if you could adapt the behaviour to avoid missing some list items at the top and bottom. However, it is your skin and your decision, I'll accept that, of course.

Another small thing: Maybe you can add the date again at the top right part, as it was in V1 for Kodi 17.

**Comment by Guilouz** [comment]
There is no problem with lists, when you are on top list :

![Image](http://i.imgur.com/TjCU2BT.jpg)

And at bottom list :

![Image](http://i.imgur.com/l4NgEV0.jpg)

And focus always stay in center of list.

**Comment by dkadioglu** [comment]
Sorry, maybe it was not that clear, what the problem is imho:
In your first screenshot, you can barely see channel 10. If you then press page down, channel 11 is now at the top of the list but, actually not readable because of the heading. In the end you've missed the information for channel 10 and channel 11. I hope, I was able to describe my problem a bit more clearly.
