### ISSUE TITLE
Translated text of msgctxt "#31029" is not shown on profile screen

### ISSUE THREAD

**Issue by rainman74** [Guilouz/repository.guilouz#81]
I've translated msgctxt "#31029", but in the profile screen it is still shown as "Last login: ..."

![31029](https://cloud.githubusercontent.com/assets/16306963/25765239/3be6a824-31ec-11e7-9ea5-2cc5c792c522.png)

--- Translation ---
#: /xml/SettingsProfile.xml
msgctxt "#31029"
msgid "Last logged in"
msgstr "Zuletzt angemeldet"

**Comment by Guilouz** [comment]
Where your screenshot is from ?

Because SettingsProfile.xml is :
![image](http://i.imgur.com/HO2qNXB.jpg)

**Comment by rainman74** [comment]
oh sorry, I mean that one:

![profile](https://cloud.githubusercontent.com/assets/16306963/25766430/ca9d40b8-31f2-11e7-8c1a-e1be7d1207df.png)

**Comment by Guilouz** [comment]
There is no string fo this translation in my MOD, you can found it in language file from Kodi :

#: xbmc/windows/GUIWindowLoginScreen.cpp
msgctxt "#20112"
msgid "Last login: {0:s}"
msgstr ""

**Comment by rainman74** [comment]
ok, but how can I translate that?

In global "resource.language.de_de" for Kodi there is:

msgctxt "#20112"
msgid "Last login: %s"
msgstr "Letzte Anmeldung: %s"

but "your" skin doesn't use that. Estuary and Estouchy uses that translation correctly. Any idea?

**Comment by Guilouz** [comment]
Your german translation file from Kodi is not updated, there is many changes in language file many weeks ago.

The correct string is : 
#: xbmc/windows/GUIWindowLoginScreen.cpp
msgctxt "#20112"
msgid "Last login: {0:s}"
msgstr ""

All '%s' have been replaced.

**Comment by rainman74** [comment]
Yes, you are right! I fixed the global language file and voila ;-)

![ok](https://cloud.githubusercontent.com/assets/16306963/25767055/b224ab76-31f6-11e7-8387-ded05ed173d2.png)

**Comment by Guilouz** [comment]
All changes for that are here : https://github.com/xbmc/xbmc/commit/2107cbc937be5fc985ba80b897af9c3ae4bbb6fd

If you use POEdit to translate, it doesn't find changes.
