### ISSUE TITLE
Translation of "Titles" in categories bar not possible

### ISSUE THREAD

**Issue by rainman74** [Guilouz/repository.guilouz#82]
Sorry for second issue, but where could I translate "Titles" ?

![titles](https://cloud.githubusercontent.com/assets/16306963/25766804/173f9202-31f5-11e7-8a3b-87ea715a64e7.png)

**Comment by Guilouz** [comment]
Same here, this string is from Kodi language file, not from my skin.
If you have translate all strings from my skin and there is not translated strings in Kodi, they are from language file of Kodi.

**Comment by rainman74** [comment]
yes! New msgid missing in global language file!

msgctxt "#10024"
msgid "Titles"
msgstr "Titel"
