### ISSUE TITLE
Wall shifted down

### ISSUE THREAD

**Issue by rainman74** [Guilouz/repository.guilouz#84]
Why did you shift the posters on every view so much down?

Is it possible to correct that back to old position? It looks very strange ... especially without the title text :-(

![skin](https://cloud.githubusercontent.com/assets/16306963/25771683/770f3eea-3258-11e7-9518-d68338f56453.png)

e.g. why did you remove the title text, too?

**Comment by Guilouz** [comment]
Because it's a MOD ^^

I have move down panel to avoid superposition with clearlogos.

Please post only issue here. There is a thread for request.
