### ISSUE TITLE
Missing texts labels

### ISSUE THREAD

**Issue by rainman74** [Guilouz/repository.guilouz#85]
Where could I translate that two missing texts? In couldn't find them ;-(

![2017-05-06_124145](https://cloud.githubusercontent.com/assets/16306963/25771727/bb0dca70-3259-11e7-8b08-8d797df5ec5a.png)
![2017-05-06_124236](https://cloud.githubusercontent.com/assets/16306963/25771726/bb0dba62-3259-11e7-9afa-57d0fa2ec891.png)

**Comment by Guilouz** [comment]
Kodi language file :

#. Label of various controls for starting playback from the beginning
#: xbmc/Autorun.cpp
#: xbmc/pvr/PVRContextMenus.cpp
#: xbmc/pvr/PVRGUIActions.cpp
#: xbmc/video/ContextMenus.cpp
#: xbmc/video/windows/GUIWindowVideoBase.cpp
msgctxt "#12021"
msgid "Play from beginning"
msgstr ""

For other, it's from Skin Helper Service addon.

Please stop post here for that.
